CREATE DATABASE IF NOT EXISTS pointofsale
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'smarteat'@'%' IDENTIFIED BY 'ROOTTOORROOT660!';
ALTER USER 'smarteat'@'%' IDENTIFIED BY 'ROOTTOORROOT660!';

GRANT ALL PRIVILEGES ON *.* TO 'smarteat'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;